title: Daily Intune & Entra Docs Reporter
description: Daily digest of changes to Microsoft's Intune, Windows Autopilot, and Entra documentation.
url: "https://reports.burgerhout.org"
baseurl: ""

github_repo: BurgerhoutJ/daily-intune-docs-reporter

permalink: /:year/:month/:day/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
